### ISSUE TITLE
macheTag() macheNacht()

### ISSUE THREAD

**Issue by Hentra** [Hentra/Zeichnung2#1]
Die Methoden sind nicht sinnvoll gestaltet, da sie auch versuchen zu agieren wenn noch nicht gezeichnet wurde und man kann macheTag() auch dann aufrufen wenn bereits Tag ist. Man müsste beide in einer Methode "aendereTageszeit()" unterbringen.

**Comment by FranekStark** [comment]
hab ich geändert!
